#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#Step 1: Construct a Fibonacci sequence not exceeding 4 million
FibSet <- c(0,1)

repeat {
  print(FibSet)
  F0 <- tail(FibSet, n=1)
  F1 <- head(tail(FibSet, n=2), n=1)
  next_number <- F0 + F1
  if ((next_number) > 4000000){
    break
  }
  FibSet <-  append(FibSet, next_number)
}

#Step 2: Sum the even values
iseven = FibSet%%2 == 0
sum(FibSet[iseven])

#Output is 4613732
